openapi: '3.0.1'
info:
  title: Mailbox API
  version: '1.0'
paths:
  /open:
    post:
      summary: Marks the mailbox as open
      responses:
        '200':
          description: Mailbox opened successfully
        '400':
          description: Bad request
  /closed:
    post:
      summary: Marks the mailbox as closed
      responses:
        '200':
          description: Mailbox closed successfully
        '400':
          description: Bad request
